### ISSUE TITLE
Single Line Lists - Padding etc

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#71] opened 2015-07-01 18:55 UTC
While this too might be a style issue - I got weary trying to search for the proper default styles you are using in the lists - particularly the single-line lists.  
- I wanted to remove the line-border 
- but also wanted each line of text (each record) to be one after the other, without so much spacing!

I could not do this easily.  The single line lists should really look like a single line list.

When I looked at the page(s) via chrome inspector, it seems like you are using a default class "project-detail" to format all the lists?  Please confirm or clarify - because this concerns me.

**Comment by yasirkhan177** [comment] 2015-07-03 01:03
actually X-programmer has pasted same style code several times in the style.css file .. i removed unwanted style code. and did adjustments to style which you asked me to do .

**Comment by cjcornell** [comment] 2015-07-03 01:14
I am not sure what you mean - but the issue still remains.

**Comment by yasirkhan177** [comment] 2015-07-03 01:18
do you want to close the gap between lists more? i mean it's a margin-bottom... i can close the gap more. i left borders on mouse hover .. if you want me to remove it ,i can . borders are removed already.

**Comment by cjcornell** [comment] 2015-07-03 01:27
Look at the way it is done is genricveryold....
the answer is
1. yes - close the gap (margins and NO borders for lists at least)
2. I want to know the CSS class so I could do it myself - I looked in the
stylesheet and it is very confuising - worse - it looks like the style for
the lists are rather inflexible (but I cannot be sure)

**Comment by yasirkhan177** [comment] 2015-07-03 01:51
i close the gap more .. you check . i'm not sure how much gap you want between each list.. 

the class is in style.css... >>> name is >>>> .project-detail .......i insert the comments as well .. before style code was messy ... now i cleaned it .

**Comment by cjcornell** [comment] 2015-07-03 01:53
1. take a look at:
http://genericveryold.cjcornell.com/createProject.php?pid=76&tab=script

2. I saw class = project-detail  ...
this worried me ... seemed that the class might be specific to projects ... and not just any list - no?

**Comment by yasirkhan177** [comment] 2015-07-03 01:55
its not specific to projects . used for list now.

**Comment by cjcornell** [comment] 2015-07-03 01:59
ok - but 
take a look at:
http://genericveryold.cjcornell.com/createProject.php?pid=76&tab=script
perhaps you can use the style they used here?
remember - this was the original intent - was to duplicate the lists used in genericveryold

**Comment by cjcornell** [comment] 2015-07-03 02:06
OK

**Comment by cjcornell** [comment] 2015-07-03 02:09
I see the other issue - it is not just one of style.  There is no way for the user (me) to tell which record my mouse is selecting ..
again take a look at 
'http://genericveryold.cjcornell.com/createProject.php?pid=76&tab=script
I am not sure how or why all the lists (including boxes) strayed so far away from the baseline look and feel, Yasir - but genericveryold is the baseline requirement for the operation.

**Comment by yasirkhan177** [comment] 2015-07-03 19:28
such thing can be achieved .. but let me finish other tasks of this milestone and then i will refine it. 


There is no way for the user (me) to tell which record my mouse is selecting .. <<< didn't get this

**Comment by cjcornell** [comment] 2015-07-03 19:30
again take a look at 
'http://genericveryold.cjcornell.com/createProject.php?pid=76&tab=script

**Comment by yasirkhan177** [comment] 2015-07-03 19:35
really not getting your point .. some times person doesn't get simple point .. maybe that's the case with me right now. can you help me out?

**Comment by cjcornell** [comment] 2015-07-03 19:50
1. Look at http://genericveryold.cjcornell.com/createProject.php?pid=76&tab=script
2. see how the single line list LOOKS?  See how the UI BEHAVES?  (mouse over etc)
3. Go to the current generic.cjcornell.com - any single line list (My Projects)
4. Does it LOOK the same as genericveryold lists?
5. Does it BEHAVE the same genericveryold lists?
6. if the answer is no ....THEN more work is required as this is not to spec.
7. go back to step 1 above. repeat until the answer to 4 and 5 are Yes.

**Comment by yasirkhan177** [comment] 2015-07-03 21:12
some of this will cover in #53 ... styling problem is not a big deal ,will be dealt. But the most important thing is the flow and logic of GPC LISTS .. before i made as it as UI for child lists.. but you said that common list layout will be set for any list whether list is a child or not... if you see script tab is a child list( in oldgeneric, which has different UI ) .. let me work on other issues of this milestone then we will be in better position to talk on this.

**Comment by cjcornell** [comment] 2015-07-03 21:24
OK.
I want this done right - with all list styles working correctly  (styles and the UI behavior)
I will a bonus to the list-improvements milestone for the extra attention to detail here and getting it done in a timely manner

**Comment by yasirkhan177** [comment] 2015-07-03 21:25
ok

**Comment by yasirkhan177** [comment] 2015-07-08 01:16
for making single line list to look like this >>>> http://genericveryold.cjcornell.com/createProject.php?pid=76&tab=script.. we need to require heading and according to it ,i will use styling to look same like genericveryold.

**Comment by cjcornell** [comment] 2015-07-08 22:02
see if you can get the style/class for the single line (and multilined) lists to have alternating background shading for each line, like genericveryold.  This is what's missing.  this is not too hard using css (I forget the actual command but there is one css parameter that will distinguish between odd and even lines of a list)

**Comment by yasirkhan177** [comment] 2015-07-09 02:23
1) :nth-child(even) <<< this is command but it is not applicable on GPC list because elements are not straight forward and lot of things done by jquery as well .. i used jquery to accomplish this(which was not too easy).

2) ... column headings are achieved by the way you tell .. but the problem is truncation which we did for single line lists .. do you want to have headings for single line lists only ? or for multi line as well?

**Comment by yasirkhan177** [comment] 2015-07-09 02:24
if you look at GUI of genericveryold ... the GUI for child table are different ( SCRIPT TAB)  as compare to single line list .. i did like this before but then you revert the changes .. now i'm bit confuse

**Comment by cjcornell** [comment] 2015-07-09 02:58
WHY are you still thinking that LISTS and Child-tables are two different things?
LISTS are lists.  If they are displaying a parent or child, GUI-wise it should not matter.

**Comment by yasirkhan177** [comment] 2015-07-09 11:36
actually ,showing list data under headings (labels) is not a straight forward task . you should move this particular task( showing list data under headings ) to another milestone . because it's not easy.

**Comment by cjcornell** [comment] 2015-07-09 16:42
OK - but you suggested the headings - i think you said they were necessary
for something (check your prior messages on this)

**Comment by yasirkhan177** [comment] 2015-07-09 22:21
actually putting headings there is not a big deal .. but we will need to handle the layout delicately .. currently ,we truncate the whole data .. means data is not as much important at the moment on the list .. the main thing is layout ,flow of GPC( data driven approach ) ,links etc .. so that's why i want it to be in another phase ,so i can give more attention .. just for the reference ... check this link >> http://genericveryold.cjcornell.com/projects.php ...... here i gave long Project name and see how layout anticipate... i handle this issue in my new build .. where you will see bit more height of cards ,but i did this to handle such behavior . i worked on the cards  in this milestone ... so that's why single line list which is very major part of GPC should be handle with extra care. That's why i want it in another milestone

**Comment by cjcornell** [comment] 2015-07-09 22:27
no problem ...   headings are not urgent as far as I know.  this can be in a new milestone.

**Comment by yasirkhan177** [comment] 2015-07-09 22:32
i know that headings are not the priority at the moment .. Thanks ..

**Closed** 2015-07-10 14:15 UTC
Labels: Not Working to Spec
